kind: Deployment
apiVersion: apps/v1
metadata:
  name: nginx-neonavi-1
  namespace: test-neonavi-nginx
  labels:
    app: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: imagebank.azurecr.io/nginx-plus/base:latest
          ports:
            - containerPort: 80
              protocol: TCP
          imagePullPolicy: Always
      restartPolicy: Always
